### ISSUE TITLE
Partially broken UI with WordPress 4.7

### ISSUE THREAD

**Issue by Grawl** [andtrev/Tuxedo-CSS-Editor#1]
![2016-12-08 14 58 42](https://cloud.githubusercontent.com/assets/846774/20998075/da87fc86-bd56-11e6-8774-d415e8b8d4a7.png)

ACE editor is showing only one line. Rolling back to previous version of WordPress just to continue developing.

Tried to fix this with CSS but with no luck.

**Comment by Grawl** [comment]
Oh wait, I fixed it… just a little.

```css
#sub-accordion-section-tux_css_editor_section {
    height: 500px !important;
}
```

I used [Web Override](http://weboverride.com/) Chrome extension to apply this style.
